##################################################
# Genotyping YAML configuration file (user)
##################################################

# Output paths, relative to snakemake --directory
snp_dir: "snps"
phase_dir: "phase"
pileup_dir: "pileup"
allele_dir: "allele"
bb_dir: "bb"
qc_dir: "qc"
log_dir: "logs"

# bulk_genotyping | single_cell_genotyping | copytyping_preprocess
workflow_mode: "bulk_genotyping"
# bulkWGS | bulkWGS-lr | bulkWES | scRNA | scATAC | VISIUM | VISIUM3prime
assay_types: ["bulkWGS"]

##################################################
# Input
sample_id: PATIENT_ID
sample_file: /path/to/samples.tsv
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

# Input for copytyping_preprocess mode
het_snp_vcf: null
bb_file: null

##################################################
# Reference
# hg19 | hg38 | chm13v2
reference_version: "hg38"
reference: /path/to/reference.fa
genome_size: /path/to/genome.sizes
region_bed: /path/to/regions.bed
window_bed: /path/to/windows.bed.gz
blacklist_bed: null
gene_blacklist_file: null
gtf_file: /path/to/genes.gtf.gz

##################################################
# Population Panel
snp_panel: /path/to/snps.vcf.gz
snp_targets: /path/to/target_positions
phasing_panel: /path/to/phasing_panel

##################################################
# Phasing
# eagle | shapeit | longphase
phaser: "shapeit"
phaser_dir: /path/to/shapeit5

##################################################
# Bias correction (bulk only)
params_count_reads:
  gc_correct: true

##################################################
# SNP filtering
params_phase_and_concat:
  min_depth: 1

##################################################
# Adaptive binning
params_combine_counts:
  min_snp_reads: 1000
  min_snp_per_block: 10
  phase_flip_test: true
  # true = median-center (ignore matched normal)
  median_normalization: false

##################################################
threads:
  genotype: 4
  phase: 4
  pileup: 8
  mosdepth: 4
