##################################################
# Genotyping YAML configuration file
##################################################
# Path to executables
bcftools: /path/to/bcftools
cellsnp_lite: /path/to/cellsnp-lite
eagle: /path/to/eagle2
shapeit: /path/to/phase_common_static
longphase: /path/to/longphase_linux-x64
mosdepth: /path/to/mosdepth
cnvkit: /path/to/cnvkit.py

# Output paths, relative to snakemake --directory
snp_dir: "snps"
phase_dir: "phase"
pileup_dir: "pileup"
allele_dir: "allele"
bb_dir: "bb"
qc_dir: "qc"
log_dir: "logs"

# bulk_genotyping | single_cell_genotyping | copytyping_preprocess
workflow_mode: "bulk_genotyping"
# bulkWGS | bulkWES | scRNA | scATAC | VISIUM | VISIUM3prime
assay_types: ["bulkWGS"]

##################################################
# Input
sample_id: sample_id
sample_file: /path/to/sample.tsv
chromosomes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

# Skip genotyping & phasing when provided
het_snp_vcf: null
# HATCHet CNV profiles and block phased haplotypes
seg_ucn: null
bbc_ucn: null
bbc_phases: null

##################################################
# Reference
# hg19 | hg38 | chm13v2
reference_version: null
reference: null
genome_size: null
region_bed: null
window_bed: null
blacklist_bed: null
wes_targets_bed: null
gene_blacklist_file: null
gtf_file: null
ref_label: "cell_type"

##################################################
# Population Panel
snp_panel_version: null
snp_panel: null
snp_targets: null
phasing_panel_version: null
phasing_panel: null

##################################################
# Genotype and pileup (single_cell_genotyping)
params_cellsnp_lite:
  # Auto | None | <tag>
  UMItag: "Auto"
  cellTAG: "CB"
  minMAF_genotype: 0
  minCOUNT_genotype: 2
  minMAF_pileup: 0
  minCOUNT_pileup: 1

params_bcftools:
  min_mapq: 20
  min_baseq: 20
  min_dp: 5
  max_depth: 1000
  min_qual: 30

##################################################
# Annotate SNP genotypes (single_cell_genotyping)
params_annotate_snps:
  min_het_reads: 2
  min_hom_dp: 10
  min_vaf_thres: 0.1
  # true | false
  filter_nz_OTH: false
  # true | false
  filter_hom_ALT: false

##################################################
# Phasing
# eagle | shapeit | longphase
phaser: "eagle"
eagle_dir:
shapeit_dir:
params_eagle:
params_shapeit:
params_longphase:
  min_mapq: 20
  extra_params: "--pb"

##################################################
params_process_anndata:
  gene_id_colname: gene_ids
  min_frac_barcodes: 5e-3
  tile_width: 200000

params_phase_and_concat:
  min_depth: 1
  gamma: 0.05
  # true | false
  exon_only: false

params_mosdepth:
  read_quality: 11
  extra_params: "--no-per-base --fast-mode"

params_count_reads:
  # true | false
  gc_correct: true
  # lowess | median
  gc_correct_method: median
  # true | false
  rt_correct: true
  samplesize: 50000
  routlier: 0.01
  doutlier: 0.001
  min_mappability: 0.9

params_combine_counts:
  min_switchprob: 1e-6
  nu: 1
  max_switchprob: 0.1
  switchprob_ps: 5e-2
  nsnp_multi: 2
  min_snp_reads: 200
  min_snp_per_block: 10

##################################################
# CNVkit parameters (bulkWES only)
params_cnvkit:
  # autobin
  method: "hybrid"
  bp_per_bin: null
  target_max_size: null
  target_min_size: null
  antitarget_max_size: null
  antitarget_min_size: null
  annotate: null
  short_names: null
  # coverage
  min_mapq: null
  # reference + fix
  no_gc: null
  no_edge: null
  no_rmask: null
  male_reference: null
  cluster: null

  # post-process cnvkit autobin+fix corrected windows.
  min_window_length: 1000

##################################################
threads:
  genotype: 4
  phase: 4
  pileup: 8
  postprocess: 2
  mosdepth: 4
  cnvkit: 4
