name: genotyping-base
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - scipy
  - numpy
  - pandas
  - numba
  - pyranges
  - pybedtools
  - matplotlib-base
  - statsmodels
  - patsy
  - anndata
  - scanpy
  - squidpy
  - tabix
  - pip
